### PR TITLE
Added support for setting center of rotation

### PR DESCRIPTION
**Pull request by Snorvarg**
Uses the css 'transform-origin' to set the center of rotation.

### CODE REVIEW

**Comment by godswearhats** [comment]
Two minor requests:
 * Please remove the comments with your name in - git makes those superfluous :-)
 * Can you also include an update to the README.md to document how to use your new functionality?

Thanks
~gwh

**Comment by godswearhats** [comment]
Closing pull request. Please re-open if you have time to make requested modifications.

**Comment by Snorvarg** [comment]
Hi, sorry I forgot completely to do the changes you requested. :O Now fixed.

**Comment by godswearhats** [comment]
Great! I'll reopen the pull request and you can commit the new changes.

**Comment by Snorvarg** [comment]
No idea how to do that! There is some 'pull request', but it says it can be done by 'project collaborators'.. 

 


     Den torsdag, 21 maj 2015 16:47 skrev godswearhats <notifications@github.com>:
   

 Great! I'll reopen the pull request and you can commit the new changes. —

**Pull request merged**
